### PR TITLE
Footer Height

### PR DESCRIPTION
**Pull request by Mumbaikar007**
solving #17 #30

### CODE REVIEW

**Comment by nikhilmufc7** [comment]
let me know when done :)

**Comment by Mumbaikar007** [comment]
done :+1:

**Comment by nikhilmufc7** [comment]
there are a few merge conflicts with the master branch, can you please resolve it, I'll merge straight after

**Comment by Mumbaikar007** [comment]
Resolved them :smile:

**Comment by nikhilmufc7** [comment]
thanks! merged

**Pull request merged**
