### PR TITLE
Revert "Remove dependencies: jQuery, Bootstrap, fullScreen.js"

### PR DESCRIPTION
**Pull request by nikhilmufc7**
Reverts nikhilmufc7/Hacktoberfest-PR#12

### CODE REVIEW

**Comment by bingocaller** [comment]
Didn't you like the changes?  
Is there anything you want done differently?

**Comment by nikhilmufc7** [comment]
Actually there were many Merge conflicts as soon as I sorted that ,it somehow changed the whole complexion of the website. Can you please refork the updated website and then add the changes, thanks a lot @bingocaller

**Comment by bingocaller** [comment]
Sure thing, I'll try! 🙂

**Comment by nikhilmufc7** [comment]
thanks

**Pull request merged**
